fix(Button):update content width
rdkcentral/Lightning-UI-Components pull request #168
Opened 2023-03-27 20:21 UTC by salhan12

## Description

The text was sliding from right to left instead of being mounted. Updated Button text sliding to be mounted. 

## References

LUI-674

## Testing

## Automation

## Checklist

- [ ] all commented code has been removed
- [ ] any new console issues have been resolved
- [ ] code linter and formatter has been run
- [ ] test coverage meets repo requirements
- [ ] PR name matches the expected semantic-commit syntax

2023-03-28 14:51 UTC, arwehrman approved these changes

2023-03-28 19:26 UTC, ImCoolNowRight approved these changes

2023-03-28 21:20 UTC, erautenberg requested changes
I'd like to wait to merge and release this so that I can test it a little more. The structure of this method seems really odd to me with this change and I want to make sure there are no side effects of never animation the width change. Also, it doesn't seem like an issue that was introduced in this PR, but the text on the Button doesn't seem quite centered, it seems like it always leans to the left.

2023-04-06 20:06 UTC, anthony9187 commented
> I'd like to wait to merge and release this so that I can test it a little more. The structure of this method seems really odd to me with this change and I want to make sure there are no side effects of never animation the width change. Also, it doesn't seem like an issue that was introduced in this PR, but the text on the Button doesn't seem quite centered, it seems like it always leans to the left.

+1 to this, if the goal is to prevent animating in some cases we should rework this method to be a little more clear about the intention. with these changes we could wind up in a situation where the short circuit prevents width from being animated but then the height still gets animated and things could be weird

2023-06-20 17:17 UTC, ChrisArasin commented
I think there's a reasonable argument that since the underlying text (and icon) elements are always "snapping" to their new sizes in a texture update, while x/y positioning may want to be smoothed, the width can always just snap to the proper size. This way, if someone updates button text to be much shorter or much longer, it is instantly positioned correctly, rather than seeing the text update with the previous position then slide into place.

2023-06-20 17:28 UTC, ChrisArasin commented
I think there also may be a decent chance you actually wouldn't want the y value (`this._Content.y`) to smooth either and just doing a patch for both would be fine... Trying to think of a time you'd want that update to smooth.... If someone patches a new height on the button, you'd want a patched update. If someone smooths the height on the button, the update methods are called on each tick so you would see this smooth to match anyway.

2023-06-20 18:26 UTC, ChrisArasin commented
Tested on a couple apps and definitely makes things look better as is.

2023-07-05 19:55 UTC, erautenberg approved these changes

2023-07-05 21:02 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Failed.

2023-07-05 21:03 UTC, merged

2023-07-06 14:58 UTC, svc-lightning-ui-components commented
:tada: This PR is included in version @lightningjs/ui-components-v2.4.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lightningjs/ui-components/v/2.4.1)
- [GitHub release](https://github.com/rdkcentral/Lightning-UI-Components/releases/tag/%40lightningjs/ui-components-v2.4.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: