Audit links/lUI 744
rdkcentral/Lightning-UI-Components pull request #172
Opened 2023-03-31 18:11 UTC by salhan12

## Description
 
updated broken links in mdx files

## References

LUI-744

## Testing

## Automation

## Checklist

- [ ] all commented code has been removed
- [ ] any new console issues have been resolved
- [ ] code linter and formatter has been run
- [ ] test coverage meets repo requirements
- [ ] PR name matches the expected semantic-commit syntax

2023-04-04 18:07 UTC, erautenberg reviewed
It looks like you may have branched from your other Button branch, so that commit is here. When you rebase, you should be able to "drop" that commit instead of "pick" it and it should remove the changes made to Button.js

2023-04-04 18:12 UTC, erautenberg requested changes
This is a good start, but if you search the entire project for `?path` and filter by just the `.mdx` files, you'll see a bunch of other links that need to be fixed. For example:
- CardSection.mdx, line 33, the path needs to be updated to "tiles-cards-card--card". You can check what the proper link is by look at the name of the component listed, in this case "Card," going to the story of that component, and looking at the URL for that docs page.

Basically, anything that starts with "elements" or "patterns" after "docs" is going to need to be updated.
<img width="685" alt="Screen Shot 2023-04-04 at 2 11 10 PM" src="https://user-images.githubusercontent.com/15019089/229881180-2caf210e-eefe-4f4b-923e-57763813f438.png">
<img width="686" alt="Screen Shot 2023-04-04 at 2 11 59 PM" src="https://user-images.githubusercontent.com/15019089/229881181-952fde5c-2a5e-4690-af3a-fb2b31b94ef3.png">
<img width="685" alt="Screen Shot 2023-04-04 at 2 11 03 PM" src="https://user-images.githubusercontent.com/15019089/229881176-c2b352a5-62c9-46f1-99a8-23325533c5a4.png">

2023-04-11 17:42 UTC, erautenberg commented
Please update your PT title to match our conventional commits requirements

2023-04-12 16:15 UTC, erautenberg approved these changes

2023-04-12 18:33 UTC, soumyaloka commented on packages/@lightningjs/ui-components/src/components/Button/Button.js
> +      this._Content.w = this._contentW;
Can we drop this commit or may be you undo changes here.

2023-04-12 19:23 UTC, soumyaloka commented on packages/@lightningjs/ui-components/src/components/NavigationManager/NavigationManager.mdx
> +NavigationManager is a is a subclass of [FocusManager](?path=/docs/navigation-focusmanager--rows),
It looks like `is a` is repeated here.

2023-04-12 20:09 UTC, soumyaloka approved these changes

2023-04-12 20:18 UTC, merged

2023-04-12 20:18 UTC, THoj13 commented on packages/@lightningjs/ui-components/src/components/Card/CardTitle.mdx
> +https://github.com/rdkcentral/Lightning-UI-Components/blob/develop/packages/%40lightningjs/ui-components/src/components/CardTitle/CardTitle.js
This link results in a 404