chore(Storybook): update default control values
rdkcentral/Lightning-UI-Components pull request #187
Opened 2023-04-14 15:15 UTC by soumyaloka

## Description

In this PR, I have updated the default value for the control and updated canvas path to make it visible in FocusManager and NavigationManager documentation.

## References

LUI-754

2023-04-20 17:22 UTC, arwehrman approved these changes

2023-04-25 18:19 UTC, THoj13 requested changes
I believe the changes to defaultValue in the Keyboard and Marquee stories files should be reverted. The defaultValue in that table should reflect what the default value of that prop is in the component, not the initial value passed to it in the story.

2023-04-25 18:19 UTC, THoj13 commented on packages/@lightningjs/ui-components/src/components/Keyboard/Keyboard.stories.js
> +      defaultValue: { summary: true }
The default value for `Keyboard.centerKeys` is `undefined` in the `Keyboard` component. I think `false` would be the more accurate value here.

2023-04-25 18:19 UTC, THoj13 commented on packages/@lightningjs/ui-components/src/components/Marquee/Marquee.stories.js
> +    table: { defaultValue: { summary: true } }
`Marquee.autoStart` by default is `false`. 
[This is where it is where that value is defaulted in the component](https://github.com/rdkcentral/Lightning-UI-Components/blob/develop/packages/%40lightningjs/ui-components/src/components/Marquee/Marquee.js#L79)

2023-04-25 20:52 UTC, THoj13 approved these changes

2023-04-26 15:50 UTC, merged