ci: swap to PAT (GH_TOKEN) for semantic release to get around branch rules
rdkcentral/Lightning-UI-Components pull request #199
Opened 2023-05-03 15:33 UTC by erautenberg

## Description

Currently, the semantic-release-bot uses the GITHUB_TOKEN instead of the GH_TOKEN, which is our service account's PAT and will have permissions to edit the branches.

@HarryLinux is going to look into whether we need `persist-credential: false`:
https://github.com/semantic-release/semantic-release/discussions/2557

2023-05-03 15:35 UTC, ImCoolNowRight approved these changes

2023-05-08 20:09 UTC, HarryLinux requested changes
from what I've been reading in [this discussion thread](https://github.com/semantic-release/semantic-release/discussions/2557), it seems we need to add `persist-credentials: false` to L23 under the checkout action `with` given that the token we're using contains permissions to push to a protected branch. Setting persist-credentials to false apparently instructs GitHub to use the token when pushing to the branch

2023-05-09 13:04 UTC, erautenberg commented
@HarryLinux thanks, updated!

2023-05-09 20:13 UTC, HarryLinux approved these changes
lgtm

2023-05-11 15:39 UTC, ImCoolNowRight commented on .github/workflows/pull-request.yml
>    quality:
I believe this is where @HarryLinux suggested we add `uses: actions/checkout@v3` to checkout the repo before we run the Quality workflow.

2023-05-18 19:02 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-05-18 19:03 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-05-18 19:17 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-05-18 19:18 UTC, merged