fix(Provider): add setVisibleCount method for out-of-bounds values.
rdkcentral/Lightning-UI-Components pull request #210
Opened 2023-05-12 15:18 UTC by soumyaloka

## Description

This PR adds a set method to the _setVisibleCount method which make sure that negative values and values outside of the bounds are not accepted

## References

LUI-731

## Testing

1. Navigate to the Provider and MetadataCardComponent.
2. Try setting the visible count value to a negative number.
3. Confirm that the value is automatically set to 1.
4. Observe that a warning message is logged to the console, stating that the visible count must be greater than or equal to 1 and vice versa for the numbers that exceeds providers length.
5. Try setting the visible count value to a number within the range of 1 to the number of providers length and confirm that the value is set correctly without any warning message being logged to the console.

2023-05-16 13:48 UTC, erautenberg approved these changes

2023-05-17 19:36 UTC, arwehrman approved these changes

2023-05-17 20:36 UTC, ImCoolNowRight requested changes
Looks great, thank you!

I tried the below code as a way to get a `console.warn` working, and I think it does the job.
```js
_setVisibleCount(count) {
  if (count < 1 || count > this.providers.length) {
    console.warn(
      "'visibleCount' must be greater than or equal to 1 and less than or equal to the number of providers."
    );
  }
  return count;
}
```

2023-05-17 20:55 UTC, soumyaloka commented
> Looks great, thank you!
> 
> I tried the below code as a way to get a `console.warn` working, and I think it does the job.
> 
> ```js
> _setVisibleCount(count) {
>   if (count < 1 || count > this.providers.length) {
>     console.warn(
>       "'visibleCount' must be greater than or equal to 1 and less than or equal to the number of providers."
>     );
>   }
>   return count;
> }
> ```

Ok, let me try that. Thanks!

2023-05-18 18:13 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-05-19 19:33 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Failed.

2023-05-23 19:44 UTC, ImCoolNowRight approved these changes

2023-05-23 19:54 UTC, merged

2023-05-25 20:10 UTC, svc-lightning-ui-components commented
:tada: This PR is included in version @lightningjs/ui-components-v2.2.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lightningjs/ui-components/v/2.2.4)
- [GitHub release](https://github.com/rdkcentral/Lightning-UI-Components/releases/tag/%40lightningjs/ui-components-v2.2.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: