docs: update Row and Column docs
rdkcentral/Lightning-UI-Components pull request #284
Opened 2023-07-14 18:37 UTC by soumyaloka

## Description

Removed the style properties from the Column and Row docs and instead referred to the properties in the NavigationManager component as they have the same style properties

## References

LUI-867

2023-07-14 18:39 UTC, soumyaloka reviewed
Thinking to remove few methods from Row and Columns which are already defined in NavigationManager and add a note in docs like
"It inherits all the methods defined in both the NavigationManager and FocusManager components".

2023-07-14 18:52 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-07-18 20:37 UTC, ImCoolNowRight requested changes

2023-07-18 20:37 UTC, ImCoolNowRight commented on packages/@lightningjs/ui-components/src/components/Column/Column.mdx
> +itemTransition: <DocsLink id="lng.Transition" />
I think this snuck its way in.

2023-07-18 20:37 UTC, ImCoolNowRight commented on packages/@lightningjs/ui-components/src/components/Column/Column.mdx
> +The Column component shares few same style properties as the one's listed in NavigationManager. For a detailed description, please refer to style properties section in the [NavigationManager componen
Can we change this to:

> The Column component shares the same style properties as the ones listed in NavigationManager. For a detailed description, please refer to style properties section in the [NavigationManager component](?path=/docs/navigation-navigationmanager--navigationmanager)

Just a change in the wording and punctuation.

2023-07-18 20:37 UTC, ImCoolNowRight commented on packages/@lightningjs/ui-components/src/components/Row/Row.mdx
> +The Row component shares the same style properties as the one's listed in NavigationManager.. For a detailed description, please refer to style properties section in the [NavigationManager component]
Pasting this here as well so they're in sync.

> The Row component shares the same style properties as the ones listed in NavigationManager. For a detailed description, please refer to style properties section in the [NavigationManager component](?path=/docs/navigation-navigationmanager--navigationmanager)

2023-07-18 20:57 UTC, ImCoolNowRight commented
> Thinking to remove few methods from Row and Columns which are already defined in NavigationManager and add a note in docs like "It inherits all the methods defined in both the NavigationManager and FocusManager components".

I think that totally makes sense and will be easier to maintain when there are updates to be made to only have one place to make them.

2023-07-19 12:43 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-07-19 13:04 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-07-19 14:08 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-07-19 15:26 UTC, erautenberg approved these changes

2023-07-19 18:27 UTC, ImCoolNowRight approved these changes

2023-07-19 18:55 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-07-19 19:12 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Passed.

2023-07-19 19:14 UTC, merged

2023-07-19 19:22 UTC, svc-lightning-ui-components commented
:tada: This PR is included in version @lightningjs/ui-components-v2.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lightningjs/ui-components/v/2.6.0)
- [GitHub release](https://github.com/rdkcentral/Lightning-UI-Components/releases/tag/%40lightningjs/ui-components-v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: