docs(Storybook): simplify Storybook sections to just Utilities and Components
rdkcentral/Lightning-UI-Components pull request #289
Opened 2023-07-19 19:43 UTC by erautenberg

## Description

The different sections in Storybook have proven to be more confusing than helpful, so condensing all stories into Docs, Utilities  (mixins) and Components. Leaving support for potential future "Patterns" and "Templates."

## References

## Testing

1. Confirm Storybook looks as expected with these new sections
2. Confirm the embedded canvases still work as expected (Docs tab of a component)

## Automation

## Checklist

- [ ] all commented code has been removed
- [ ] any new console issues have been resolved
- [ ] code linter and formatter has been run
- [ ] test coverage meets repo requirements
- [ ] PR name matches the expected semantic-commit syntax

2023-07-19 20:00 UTC, ImCoolNowRight requested changes

2023-07-19 20:00 UTC, ImCoolNowRight commented on packages/@lightningjs/ui-components/src/mixins/withLayout/withLayout.mdx
> +  <Story id="utilities--withlayout--with-layout" />
Not going to comment on them all, but this extra hyphen is causing all of the utilities stories to not load in the docs.

2023-07-19 20:43 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Failed.

2023-07-19 21:18 UTC, soumyaloka commented on packages/@lightningjs/ui-components/src/components/Control/Control.mdx
> +`Control` contains the same style properties as [Button](?path=/docs/components-button--button) in additional to a couple other style properties listed below:
Path for the button works fine in the style properties, but is not working in properties section, also noticed they are few other spots that needs to be updated like in TitleRow, Control and few other component docs.
I can submit another quick PR to update those.

2023-07-19 22:06 UTC, arwehrman commented
A heads up, a lot of this changes in v7.

- We can't use the variables in Titles or in story sorting. See my comments on my v7 pr about that 
- We no longer use the <Canvas> in the docs

I can make these updates in v7 but just wanted to be mindful if we do any future changes like this before v7 is merged in.

2023-07-21 12:19 UTC, erautenberg commented on packages/@lightningjs/ui-components/src/mixins/withLayout/withLayout.mdx
> +  <Story id="utilities--withlayout--with-layout" />
Fixed, thanks!

2023-07-21 12:25 UTC, erautenberg commented
@arwehrman I'm not sure when we're merging that PR, so I'd like to get these in regardless to make things cleaner for AirUI. Quick find and replaces on your shouldn't be too bad anyway and I can help if you need.

> * We can't use the variables in Titles or in story sorting. See my comments on my v7 pr about that

Why can't we used variables anymore? I read your post and looked at the migration guide and understand that the sort function needs to be self-contained so we can't use variables _there,_ but the stories themselves are still just JS and should still be able to import the categories without issue.

> * We no longer use the  in the docs

What do you mean by the second bullet, looks like a word is missing?

2023-07-21 13:19 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Failed.

2023-07-21 14:20 UTC, arwehrman commented
`title`  in v7 is optional and if left out it will use the files location. Also `title` can only be a string  see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#string-literal-titles
In v7, we could move everything into sub-folders, so Utilities, Docs, Components, and other future categories. Then SB would use that sub-folder as the category for the title automatically.

Second part about the Docs, not putting <Canvas> in the Docs.  We can, but I thought we wanted to remove them. Not super important for this PR but just something to keep in mind.

2023-07-21 14:26 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Failed.

2023-07-21 18:41 UTC, soumyaloka commented on packages/@lightningjs/ui-components/src/components/Control/Control.mdx
> +`Control` contains the same style properties as [Button](?path=/docs/components-button--button) in additional to a couple other style properties listed below:
I have created a ticket for this, may be after merging this PR and Mandy's PR. That should be ready to be picked. https://ccp.sys.comcast.net/browse/LUI-939

2023-07-21 21:00 UTC, erautenberg commented
> `title` in v7 is optional and if left out it will use the files location. Also `title` can only be a string see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#string-literal-titles In v7, we could move everything into sub-folders, so Utilities, Docs, Components, and other future categories. Then SB would use that sub-folder as the category for the title automatically.
> 
> Second part about the Docs, not putting in the Docs. We can, but I thought we wanted to remove them. Not super important for this PR but just something to keep in mind.

Wow this is so wild. Why is Storybook making that so strict, it seems odd if it all boils down to a string in the end 🙄 Is it OK to keep this for now and in your upgrade PR we can just do a find and replace on everything or does that create too much rework?

2023-07-21 21:09 UTC, ImCoolNowRight approved these changes

2023-07-24 14:45 UTC, soumyaloka commented on packages/@lightningjs/ui-components/src/components/Tile/Tile.mdx
> +| progressBar        | object  | false    | undefined  | Object containing all properties supported in the [ProgressBar component](??path=/docs/utilities-progressbar--progress-bar)
We have to change path for progressBar and Checkbox, they are pointed to utilities here.

2023-07-24 14:51 UTC, soumyaloka commented on packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.mdx
>  | provider    | [Provider](?path=/docs/utilities-provider--provider) | false    | undefined | an object of [Provider](?path=/docs/utilities-provider--provider) properties to patch in |
Same here need to replace with components.

2023-07-24 14:54 UTC, soumyaloka commented on packages/@lightningjs/ui-components/src/components/MetadataCardContent/MetadataCardContent.mdx
>  | provider    | [Provider](?path=/docs/utilities-provider--provider) | false    | undefined | an object of [Provider](?path=/docs/utilities-provider--provider) properties to patch in |
In CardRadio, we need change the path for Radio from utilities to components

2023-07-24 15:02 UTC, soumyaloka approved these changes

2023-07-24 22:13 UTC, svc-lightning-ui-components commented
Sanity Tests Execution Failed.

2023-07-25 15:26 UTC, merged

2023-07-27 21:31 UTC, svc-lightning-ui-components commented
:tada: This PR is included in version @lightningjs/ui-components-v2.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lightningjs/ui-components/v/2.7.0)
- [GitHub release](https://github.com/rdkcentral/Lightning-UI-Components/releases/tag/%40lightningjs/ui-components-v2.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: