fix: updates to fix merge order issue
rdkcentral/Lightning-UI-Components pull request #413
Opened 2023-11-16 20:16 UTC by joshhowenstine

## Description

## References

## Testing

## Automation

## Checklist

- [ ] all commented code has been removed
- [ ] any new console issues have been resolved
- [ ] code linter and formatter has been run
- [ ] test coverage meets repo requirements
- [ ] PR name matches the expected semantic-commit syntax

2023-11-16 20:33 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-16 20:55 UTC, ImCoolNowRight approved these changes
Minor comment, but this did the trick! 🙌🏼

2023-11-16 20:55 UTC, ImCoolNowRight commented on packages/@lightningjs/ui-components/src/mixins/withThemeStyles/utils.js
> +    'unfocused' // Focused must be at the end for proper fallback since base === 'unfocused' in many cases
Should this be "Unfocused must be..."?

2023-11-17 16:02 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-21 14:43 UTC, erautenberg commented on packages/@lightningjs/ui-components/src/mixins/withThemeStyles/utils.test.js
> +      disabled_brand: { color: 'primary', selected: { color: 'brand' } }
I'm a little confused by this test and the result having "selected" nested inside of the default mode/tones. This test reads more like just adding a custom property that is an object versus adding a mode or tone of "selected." Is that the expectation?

2023-11-21 14:58 UTC, erautenberg requested changes
I added this to ListItem.stories.js and when set in the inverse tone and selected mode, nothing seems to happen:
```js
          style: {
            tone: {
              inverse: {
                mode: {
                  selected: {
                    backgroundColor: 0xff00ff00
                  }
                }
              }
            }
          }
```

This works fine when in selected and not nesting in a tone:
```js
          style: {
            mode: {
              selected: {
                backgroundColor: 0xff00ff00
              }
            }
          }
```

2023-11-23 17:40 UTC, svc-lightning-ui-components commented
Test Execution Passed.

2023-11-27 22:48 UTC, svc-lightning-ui-components commented
Test Execution Passed.

2023-11-28 20:02 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-28 20:21 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-29 16:21 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-29 17:39 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-29 18:23 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-29 23:16 UTC, svc-lightning-ui-components commented
Test Execution Passed.

2023-11-30 00:32 UTC, erautenberg approved these changes

2023-11-30 20:35 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 20:57 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 21:05 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 21:08 UTC, merged

2023-11-30 21:13 UTC, svc-lightning-ui-components commented
:tada: This PR is included in version @lightningjs/ui-components-v2.18.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lightningjs/ui-components/v/2.18.0)
- [GitHub release](https://github.com/rdkcentral/Lightning-UI-Components/releases/tag/%40lightningjs/ui-components-v2.18.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: