fix: allow componentConfig props to properly merge with component props
rdkcentral/Lightning-UI-Components pull request #416
Opened 2023-11-20 17:19 UTC by joshhowenstine

## Description

## References

## Testing

## Automation

## Checklist

- [ ] all commented code has been removed
- [ ] any new console issues have been resolved
- [ ] code linter and formatter has been run
- [ ] test coverage meets repo requirements
- [ ] PR name matches the expected semantic-commit syntax

2023-11-20 17:35 UTC, svc-lightning-ui-components commented
Test Execution Passed.

2023-11-20 19:23 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-20 19:34 UTC, ImCoolNowRight approved these changes

2023-11-21 15:05 UTC, arwehrman commented
I created a build and pulled it into IS. Everything looks ok but there are a few tests failing. Looks like there all variations of Rail so not sure if this related to your changes or not.

2023-11-21 15:09 UTC, erautenberg requested changes
I ran a `yarn build` and copied the dist over to IS LUI and the `imageScale` doesn't seem to be applied correctly at all anymore, no matter the theme. In the Tile story in the Xfinity theme, nothing seems to happen when swapping between focus and unfocus when it should be scaling. On the Rail story, if I start on the Xfinity theme, it seems like the first tile in the rail is stuck in the scaled up view, and if I switch to Mosaic, it is still stuck that way as well.

2023-11-29 17:18 UTC, closed without merging