feat(Keyboard): calculate key size based on base key width
rdkcentral/Lightning-UI-Components pull request #421
Opened 2023-11-27 18:41 UTC by THoj13

## Description
This changes how the width of `Key` components is calculated so that each Key's width is a multiple of the smallest key width (plus the spacing between keys). This results in the left and right borders of each key aligning with the borders of keys above and below it.

## References
LUI-1191

## Testing
1. View the  Keyboard stories
2. All keys widths should be multiples of the smallest key's width. A way to see this is to view the keyboard not center aligned and the left/right borders should align. 

## Automation
If automation is checking widths of keys, there may be changes required for this.

## Checklist

- [x] all commented code has been removed
- [x] any new console issues have been resolved
- [x] code linter and formatter has been run
- [x] test coverage meets repo requirements
- [x] PR name matches the expected semantic-commit syntax

2023-11-27 18:58 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-27 19:04 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-28 16:40 UTC, erautenberg requested changes
Overall looks good! I'd just like to rearrange where things live and ensure we don't create an breaking changes in the styles. So `sizes` should still live there. Instead, it will just include the multiple number, like this:
```js
sizes: {
  sm: 1,
  md: 2,
  lg: 3,
  xl: 4,
  xxl: 5
}
```
Then in the Key class, you would do `this.style.baseWidth * this.style.sizes[this.size] + this.style.keySpacing * (this.style.sizes[this.size] - 1)`

2023-11-28 16:45 UTC, erautenberg commented
Also, can the use pass in a hard-set width? Like if size is a number (check out columnSize in Gallery)

2023-11-29 22:07 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-29 22:25 UTC, THoj13 commented
> Also, can the user pass in a hard-set width? Like if size is a number (check out columnSize in Gallery). Or, could they just pass in a width directly to the Key and apply that? Maybe like the fixedWidth part of Button?

Good point. Key extends Button, so I think it'd makes sense for it to follow the same API (setting `fixed: true` to allow defining `w` on it).

2023-11-29 22:26 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-29 22:41 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 00:30 UTC, erautenberg commented on packages/@lightningjs/ui-components/src/components/Key/Key.mdx
> -| sizes      | object           | used to determine the width of key, contains the properties `sm`, `md`, `lg`, `xl`     |
I think the `sizes` line needs to be brought back

2023-11-30 00:30 UTC, erautenberg commented on packages/@lightningjs/ui-components/src/components/Key/Key.mdx
> +| size       | string   | false    | sm        | Used to determine the with of the key. Accepts: `sm`, `md`, `lg`, `xl`, `xxl`.
this can be removed/move back to style props

2023-11-30 16:10 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 16:30 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 17:06 UTC, THoj13 commented
> Also, can the user pass in a hard-set width? Like if size is a number (check out columnSize in Gallery). Or, could they just pass in a width directly to the Key and apply that? Maybe like the fixedWidth part of Button?

Good call out. I ended up following the same API for a fixed width Button (9623561b8e1fd35dac7f0aabe727bd626e24aa49)

2023-11-30 17:19 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 17:26 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 20:16 UTC, ImCoolNowRight reviewed
Everything looks great! Just realized that the TS definitions are going to need to be updated for the new properties and styles.

2023-11-30 20:16 UTC, erautenberg approved these changes

2023-11-30 20:39 UTC, ImCoolNowRight approved these changes

2023-11-30 20:46 UTC, svc-lightning-ui-components commented
Test Execution Failed.

2023-11-30 20:47 UTC, merged

2023-11-30 21:13 UTC, svc-lightning-ui-components commented
:tada: This PR is included in version @lightningjs/ui-components-v2.18.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lightningjs/ui-components/v/2.18.0)
- [GitHub release](https://github.com/rdkcentral/Lightning-UI-Components/releases/tag/%40lightningjs/ui-components-v2.18.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: