Feat/with announcer
rdkcentral/Lightning-UI-Components pull request #64
Opened 2021-09-21 19:05 UTC by THoj13

- adds `withAnnouncer` mixin
- updates storybook preview to wrap components with `withAnnouncer`

2021-09-21 19:45 UTC, THoj13 commented
@erautenberg Should `Announcer` be removed with this update or is there plans to support it along with `withAnnouncer`?

2021-09-23 13:58 UTC, chelseasimek requested changes
This same code is in elements right now as well...we should deprecate that in this PR as well

2021-09-23 14:54 UTC, THoj13 commented
> This same code is in elements right now as well...we should deprecate that in this PR as well

@chelseasimek Sounds good. `elements/Announcer` has now been removed in favor of `mixins/withAnnouncer`

2021-09-23 17:27 UTC, chelseasimek approved these changes

2021-09-24 18:41 UTC, anthony9187 approved these changes

2021-09-24 18:51 UTC, merged