feat(Slider): add Slider element
rdkcentral/Lightning-UI-Components pull request #79
Opened 2021-10-12 19:08 UTC by THoj13

- moved `FadeShader` to `textures/` , exported from root
- added `Slider` element

2021-10-15 15:03 UTC, anthony9187 commented on textures/index.js
> +export { FadeShader, Circle, Arrow };
can we split these out to separate files and export them from the textures/index.js?

2021-10-15 17:14 UTC, THoj13 commented on textures/index.js
> +export { FadeShader, Circle, Arrow };
Can do!

2021-10-20 13:36 UTC, anthony9187 approved these changes

2021-10-20 13:58 UTC, erautenberg requested changes
This is on a white background for me. Is that true for anyone else? Shouldn't it be a white slider on black background?

2021-10-20 16:30 UTC, anthony9187 commented
> This is on a white background for me. Is that true for anyone else? Shouldn't it be a white slider on black background?

I'm seeing this as well, can we update this so the story matches the others?

2021-10-21 13:08 UTC, THoj13 commented
> > This is on a white background for me. Is that true for anyone else? Shouldn't it be a white slider on black background?
> 
> I'm seeing this as well, can we update this so the story matches the others?

Updated

2021-10-21 17:36 UTC, erautenberg approved these changes

2021-10-21 17:49 UTC, merged